if exists (select * from dbo.sysobjects where id = object_id(N'Audit') and OBJECTPROPERTY(id, N'IsUserTable') = 1) drop table Audit

   create table Audit (
      Id UNIQUEIDENTIFIER not null,
       DocumentId NVARCHAR(50) null,
       DocumentCode NVARCHAR(50) null,
       CaseFolderId NVARCHAR(50) null,
       CaseFolderCode NVARCHAR(50) null,
       FieldId NVARCHAR(50) null,
       FieldCode NVARCHAR(50) null,
       HolderCode NVARCHAR(50) null,
       InferenceModel NVARCHAR(50) null,
       AreaInference NVARCHAR(50) null,
       PorConfInference NVARCHAR(50) null,
       ConfiableInference NVARCHAR(50) null,
       FiableInference NVARCHAR(50)null,
       FechaInference NVARCHAR(50)null,
       AuthorInference NVARCHAR(50)null,
       PositionInference NVARCHAR(50)null,
       AreaSelect NVARCHAR(50)null,
       PorConfSelect NVARCHAR(50)null,
       ConfiableSelect NVARCHAR(50)null,
       FiableSelect NVARCHAR(50)null,
       FechaSelect NVARCHAR(50)null,
       AuthorSelect NVARCHAR(50)null,
       PositionSelect NVARCHAR(50)null,
       ApproveSuper NVARCHAR(50)null,
       AreaSuper NVARCHAR(50)null,
       PorConfSuper NVARCHAR(50)null,
       ConfiableSuper NVARCHAR(50)null,
       FiableSuper NVARCHAR(50)null,
       FechaSuper NVARCHAR(50)null,
       AuthorSuper NVARCHAR(50)null,
       PositionSuper NVARCHAR(50)null,
       TypeAction NVARCHAR(50)null,
       LogId NVARCHAR(50)null,
       Qualification NVARCHAR(50)null,
       primary key (Id)
    )  
